### ISSUE TITLE
针对个别傻逼的迷惑发言提出警告！

### ISSUE THREAD

**Issue by rcy1314** [rcy1314/jsd.cdn#1]
第一，爱用不用，不对你有任何爱心及同情心泛滥！
第二，请自查自纠，再来跟我提什么协议！
<img width="765" alt="@xiaojiang233的傻逼言论" src="https://github.com/user-attachments/assets/203fd511-481f-4a7a-8479-3915a459b296">

**Comment by rcy1314** [comment]
<img width="765" alt="1725073651317" src="https://github.com/user-attachments/assets/8005cc1a-8918-48bb-a708-17d5635e9445">

**Comment by xiaojiang233** [comment]
![a96b2c3e90cc8a835738cdee05aa9ff8](https://github.com/user-attachments/assets/91265aa9-0ccc-42a9-9990-712509a37e31)
你甚至不愿意删除commit记录
改域名谁不会
![8dc0e300c6c495dacfc225b1af94aba2](https://github.com/user-attachments/assets/e432d97e-91fd-44b4-8c24-13cf484de622)
![b0513d88953ca00dd11bc7b6592bb296](https://github.com/user-attachments/assets/105a8221-c6ce-4a0e-9758-ec01fde30c82)
这更改的时间也太巧了吧，还有我的Issues呢，这是不是从侧面反映了你急了？

**Comment by rcy1314** [comment]
@xiaojiang233 OK，满足你，我会关闭开源，还有，别来恶心我
