### ISSUE TITLE
请尊重原作者，标明出处

### ISSUE THREAD

**Issue by xiaojiang233** [rcy1314/jsd.cdn#2]
根据mit协议，你需要标注原作者及出处
https://github.com/rong6/jsd

**Comment by rcy1314** [comment]
@xiaojiang233 麻烦你看下代码中所有的域名指向，再麻烦你看下代码中的nginx.conf解析
<img width="833" alt="1725072441451" src="https://github.com/user-attachments/assets/363be421-6c98-4d3a-a296-8654fc45acff">
